#!/bin/bash

# Http-Authentication Plugin
# Syntax: httpauth <option> <argument>
# Options: -add, -delete, -list, -wp-admin, -whitelist, -whitelist-remove
# Arguments: -raw

source /opt/webinoly/lib/general
check_for_parameters $@

if [[ $(conf_read nginx) != "true" && ( -n $add || -n $delete || -n $list || -n $whitelist || -n $whitelist_remove ) ]]; then
	echo "${red}[ERROR] NGINX is required to get HTTP Authentication working properly! ${end}"
	exit 1
fi


if [[ -n $add ]]; then
	if [[ $add == true ]]; then
		echo ""
		read -p "${blu}HTTP-Auth User: ${end}" user
		read -p "${blu}HTTP-Auth Password: ${end}" pass
		echo ""
	elif [[ $(echo "${add}" | cut -c-1) == "[" && $(echo "${add}" | rev | cut -c-1) == "]" ]]; then
		userdata=${add:1:-1}
		user=$(echo "${userdata}" | cut -d',' -f 1 -s)
		pass=$(echo "${userdata}" | cut -d',' -f 2 -s)
	else
		echo "${red}[ERROR] Please enter a valid value for username and password!${end}"
		exit 1
	fi
	
	if ! [[ -n $user && -n $pass && $user =~ ^[^:]+$ && $pass =~ ^[^:]+$ ]]; then
		echo "${red}Please, enter a valid username and password!${end}"
		exit 1
	fi
	
	[[ -a /etc/nginx/.htpasswd ]] && exist=$( grep -E "^${user}:" /etc/nginx/.htpasswd )
	if [[ -z $exist ]]; then
		sudo sh -c "echo -n '$user:$(openssl passwd -1 $pass)\n' >> /etc/nginx/.htpasswd"
		echo "${gre}User '$user' has been added successfully!${end}"
	else
		echo "${red}User '$user' already exist!${end}"
	fi
	echo ""

	
elif [[ -n $delete ]]; then
	[[ $delete == true ]] && read -p "${blu}HTTP-Auth User: ${end}" userpurge || userpurge=$delete
	[[ -a /etc/nginx/.htpasswd ]] && exist=$( grep -F "${userpurge}:" /etc/nginx/.htpasswd )
	if [[ -z $exist ]]; then
		echo "${red}User '$userpurge' does not exist!${end}"
		exit 1
	fi
	sudo sed -i "/^$userpurge:/d" /etc/nginx/.htpasswd
	echo "${gre}User '$userpurge has been deleted successfully!${end}"

	
elif [[ -n $list ]]; then
	echo ""
	if [[ -a /etc/nginx/.htpasswd ]]; then
		cat /etc/nginx/.htpasswd | 
		{
		while read line
		do
			# Show only the user_name part, cut encrypted password string
			[[ $list == "raw" || -n $raw ]] && echo "$line" | cut -f 1 -d ':' || echo "${gre}+ $(echo $line | cut -f 1 -d ':') ${end}"
			nonemptylist=true
		done
		[[ -z $nonemptylist && -z $raw && $list != "raw" ]] && echo "${blu}[Empty] No users were found!${end}"
		}
	fi
	echo ""

	
elif [[ -n $wp_admin_on || -n $wp_admin_off || -n $wp_admin ]]; then
	[[ $(conf_read nginx) == "true" ]] && iswpadon=$( grep -F "acl.conf;" /etc/nginx/common/wpcommon.conf )
	if [[ -n $wp_admin_on || $wp_admin == "on" ]]; then
		if [[ -z $iswpadon ]]; then
			if [[ $(conf_read nginx) == "true" ]]; then
				sudo sed -i "/\/wp-login\.php/a \include common/acl.conf;" /etc/nginx/common/wpcommon.conf
				sudo sed -i "/\/wp-admin\/\./a \include common/acl.conf;" /etc/nginx/common/wpcommon.conf
				sudo service nginx reload
			fi
			conf_write wp-admin-auth true
			echo "${gre}WordPress Admin HTTP Authentication has been enabled! ${end}"
		else
			echo "${gre}HTTP Authentication for WP Admin pages is already enabled! ${end}"
		fi
	
	elif [[ -n $wp_admin_off || $wp_admin == "off" ]]; then
		if [[ -n $iswpadon || ( -z $iswpadon && $(conf_read nginx) != "true" ) ]]; then
			if [[ $(conf_read nginx) == "true" ]]; then
				sudo sed -i "/acl.conf/d" /etc/nginx/common/wpcommon.conf
				sudo service nginx reload
			fi
			conf_write wp-admin-auth purged
			echo "${gre}WordPress admin authentication has been disabled! ${end}"
		else
			echo "${gre}HTTP Authentication for WP Admin pages is already disabled! ${end}"
		fi
	else
		echo "${red}[ERROR] Invalid option! ${end}"
		exit 1
	fi


elif [[ -n $whitelist ]]; then
	if [[ -a /etc/nginx/common/acl.conf ]]; then
		[[ $whitelist == true ]] && read -p "${blu}IP address to whitelist: ${end}" whitelist
		if [[ $(ip_check $whitelist) == "true" ]]; then
			exist=$( grep -E "^allow $whitelist;$" /etc/nginx/common/acl.conf )
			if [[ -z $exist ]]; then
				sudo sed -i "/deny all;/i \allow ${whitelist};" /etc/nginx/common/acl.conf
				sudo service nginx reload
				echo "${gre}The IP address ${blu}'$whitelist'${gre} was successfully whitelisted!${end}"
			else
				echo "${red}IP '$whitelist' is already whitelisted!${end}"
				exit 1
			fi
		else	
			echo "${red}[ERROR] Please, enter a valid IP value!${end}"
			exit 1
		fi
	else
		echo "${red}[ERROR] Nginx file not found!${end}"
		exit 1
	fi


elif [[ -n $whitelist_remove ]]; then
	if [[ -a /etc/nginx/common/acl.conf ]]; then
		[[ $whitelist_remove == true ]] && read -p "${blu}IP address to remove from whitelist: ${end}" whitelist_remove
		if [[ $(ip_check $whitelist_remove) == "true" ]]; then
			# https://stackoverflow.com/questions/1797906/delete-using-a-different-delimiter-with-sed
			sudo sed -i "\#^allow ${whitelist_remove};#d" /etc/nginx/common/acl.conf
			sudo service nginx reload
			echo "${gre}The IP address ${blu}'$whitelist_remove'${gre} was successfully removed from whitelist!${end}"
		else
			echo "${red}Please, enter a valid IP value!${end}"
			exit 1
		fi
	else
		echo "${red}[ERROR] Nginx file not found!${end}"
		exit 1
	fi	

	
else
	echo "${red}[ERROR] Please enter a valid option!${end}"
	exit 1
fi
