#!/bin/bash

# Site Manager Plugin (Create, delete and de/activate)
# Syntax: site <domain> <option> <argument>
# Options: -html, -php, -mysql, -wp, -wpsubdir, -wpsubdom, -parked, -proxy, -on, -off, -delete, -delete-all, -list, -cache, -ssl, -force-redirect, -yoast-sitemap, -multisite-convert, -clone-from, -replace-content, -redirection
# Arguments: -cache, -root, -root-path, -subdomain, -ignore-ssl, -wildcard, -raw, -external-db, -revoke, -ssl-crt, -ssl-key, -ssl-ocsp, -subfolder, -from, -to, -http-code, -regex

# shopt is necessary for this kind !(html|22222) of patterns
shopt -s extglob

source /opt/webinoly/lib/sites
check_for_parameters $@
api-events_update sis
check_for_nginx -ask


# Check if site is sub-domain
if [[ -n $domain ]]; then
	count=1
	while true; do
		tld=$(echo "${domain}" | rev | cut -d'.' -f -$count -s | rev)
		if ! grep -Fxq "$tld" /opt/webinoly/lib/public_suffix_list.dat; then
			break
		fi
		count=$[$count+1]
	done
	[[ -n $(echo "$(echo "${domain}" | rev | cut -d'.' -f $count- -s | rev)" | cut -d'.' -f 2 -s) || $count == 1 ]] && subdomflag="1" || subdomflag="0"
fi
# Get variables with sub-domain info
if [[ $subdomflag == 1 ]]; then
	main_domain=$(echo "${domain}" | rev | cut -d'.' -f -$count -s | rev)
	sub_domain=$(echo "${domain}" | rev | cut -d'.' -f $[$count+1]- -s | rev)
fi
# Overwrite value if defined by user
[[ $subdomain == "true" ]] && subdomflag="1"
[[ $subdomain == "false" ]] && subdomflag="0"


# Evaluate if site to create is WP ( 0 = noWP, 1 = WP ask, 2 = WP default, 3 = WP unattended, 4 = MySQL default, 5 = MySQL unattended )
type="0"
if [[ -n $wp || -n $wpsubdir || -n $wpsubdom || -n $mysql ]]; then
	[[ -n $mysql ]] && type="4" || type="2"

	# For legacy support
	[[ $wp == "default"  ]] && wp=true
	[[ $wpsubdir == "default"  ]] && wpsubdir=true
	[[ $wpsubdom == "default"  ]] && wpsubdom=true
	[[ $mysql == "default"  ]] && mysql=true

	if [[ ( -n $wp && $wp != true ) || ( -n $wpsubdir && $wpsubdir != true ) || ( -n $wpsubdom && $wpsubdom != true ) || ( -n $mysql && $mysql != true ) ]]; then
		if [[ $wp == "custom" || $wpsubdir == "custom" || $wpsubdom == "custom" || $mysql == "custom" ]]; then
			[[ -n $mysql ]] && type="0" || type="1"
		else
			[[ -n $wp && $wp != true  ]] && value=$wp
			[[ -n $wpsubdir && $wpsubdir != true  ]] && value=$wpsubdir
			[[ -n $wpsubdom && $wpsubdom != true  ]] && value=$wpsubdom
			[[ -n $mysql && $mysql != true  ]] && value=$mysql
			
			# -wp=[setupmysql,setupwp,dbhost,dbname,dbuser,dbpass,dbpref,extdbuser,extdbpass]
			custombegin=$(echo "${value}" | cut -c-1)
			customlast=$(echo "${value}" | rev | cut -c-1)
			if [[ $custombegin == "[" && $customlast == "]" || $mysql == true ]]; then
				wpdata=${value:1:-1}
			else
				echo "${red}[ERROR] Please enter a valid custom value!${end}"
				exit 1
			fi
			
			# Because MySQL format not have this parameters at the beggining to match WP format. Insert it!
			if [[ -n $mysql && $mysql != true ]]; then
				wpdata=${wpdata/#/true,false,}
				# Insert wp_prefix if external db data is found.
				extdata=$(echo "${wpdata,,}" | cut -d',' -f 7- -s)
				if [[ -n $extdata ]]; then
					wpdata=$(echo "${wpdata,,}" | cut -d',' -f -6 -s)
					wpdata=${wpdata/%/,false,}
					wpdata=${wpdata/%/$extdata}
				fi
			fi
			
			# Double coma is for lower case convertion
			setmsqcustom=$(echo "${wpdata,,}" | cut -d',' -f 1 -s)
			setpwpcustom=$(echo "${wpdata,,}" | cut -d',' -f 2 -s)
			
			dbhostcustom=$(echo "${wpdata}" | cut -d',' -f 3 -s)
			dbnamecustom=$(echo "${wpdata}" | cut -d',' -f 4 -s)
			dbusercustom=$(echo "${wpdata}" | cut -d',' -f 5 -s)
			dbpasscustom=$(echo "${wpdata}" | cut -d',' -f 6 -s)
			dbprefcustom=$(echo "${wpdata}" | cut -d',' -f 7 -s)
			exusercustom=$(echo "${wpdata}" | cut -d',' -f 8 -s)
			expasscustom=$(echo "${wpdata}" | cut -d',' -f 9 -s)
			
			[[ ${dbpasscustom,,} == "random" ]] && dbpasscustom=`pwgen -s -1 16`
			
			# Check if we have ALL the parameters.
			if [[ $mysql != true && ( -z $setmsqcustom || -z $setpwpcustom || -z $dbhostcustom || -z $dbnamecustom || -z $dbusercustom || -z $dbpasscustom || ( -z $dbprefcustom && -z $mysql && -z $extdata ) || ( -n $exusercustom && -z $expasscustom )) ]]; then
				echo "${red}[ERROR] Missing parameters!${end}"
				exit 1
			fi
			
			if [[ $custombegin == "[" && $customlast == "]" && ((($setmsqcustom == "true" || $setpwpcustom == "true") && -n $dbhostcustom && -n $dbnamecustom && -n $dbusercustom && -n $dbpasscustom && (-n $dbprefcustom || ( -n $mysql && $mysql != true ))) || ($setmsqcustom == "false" && $setpwpcustom == "false")) ]]; then
				[[ -n $mysql && $mysql != true ]] && type="5" || type="3"
			fi
		fi
	fi
fi

# Check for valid WP subfolder
[[ -z $subfolder ]] && subfolder=""
if [[ -n $subfolder && ! ( $subfolder =~ ^\/([A-Za-z0-9_\/\-]+)?[^\/]$ ) ]]; then
	echo "${red}[ERROR] Please, enter a valid value for subfolder!${end}"
	exit 1
elif [[ -n $subfolder && $type != [123] && -z $delete && -z $cache && -z $yoast_sitemap && -z $multisite_convert && -z $clone_from && -z $replace_content ]]; then
	echo "${red}[ERROR] Subfolder option is only supported for WordPress sites!${end}"
	exit 1
elif [[ -n $subfolder && ( -n $delete || -n $cache || -n $yoast_sitemap || -n $multisite_convert || -n $clone_from || -n $replace_content ) && ! -d /var/www/$domain/htdocs$subfolder ]]; then
	echo "${red}[ERROR] Subfolder not found!${end}"
	exit 1
else
	subname=$(echo $subfolder | sed "s/\//_/g")
fi
# Check for stack packages
[[ $type == [123] || -n $php ]] && check_for_php -ask
[[ $type == [24] ]] && check_for_mysql -ask


	
# Delete all sites
if [[ -n $delete_all ]]; then
	api-events_update si7
	delete_all_sites

	
# Create PHP site
elif [[ -n $php && -n $domain ]]; then
	createsite
	
	
# Create MYSQL site
elif [[ -n $mysql && -n $domain ]]; then
	# We use WP function to create DB when type=0 WP files are not installed.
	createsite
	wpinstall
elif [[ -n $mysql && -z $domain ]]; then
	# Hack to create a DB easily (without site).
	wpinstall


# Create HTML site
elif [[ -n $html && -n $domain ]]; then
	createsite
	sudo sed -i '/index/c \	index  index.html index.htm;' /etc/nginx/sites-available/$domain
	sudo sed -i '/index/a \	location / { try_files $uri $uri/ =404; }' /etc/nginx/sites-available/$domain
	sudo sed -i '/php.conf/d' /etc/nginx/sites-available/$domain


# Create WP site
elif [[ -n $wp && -n $domain ]]; then
	if [[ -z $subfolder ]]; then
		createsite
		sudo sed -i '/locations.conf/i \	include common/wpcommon.conf;' /etc/nginx/sites-available/$domain
		[[ $(conf_read wp-admin-auth) == "purged" ]] && sudo httpauth $domain -wp-admin=off > /dev/null 2>&1
		[[ $(conf_read yoast-sitemap) != "purged" ]] && sudo site $domain -yoast-sitemap=on > /dev/null 2>&1
	else
		if [[ -f /etc/nginx/sites-available/$domain && -n $subfolder && $type == [123] && -d /var/www/$domain/htdocs$subfolder ]]; then
			echo "${red}[ERROR] Subfolder ${blu}'$subfolder'${red} already exists!${end}"
			exit 1
		elif [[ -f /etc/nginx/sites-available/$domain && -n $subfolder && $type == [123] && ! -d /var/www/$domain/htdocs$subfolder ]]; then
			wpinstall
		else
			createsite
		fi
		
		wp_subfolder
	fi


# Convert WP single to Multisite
elif [[ -n $multisite_convert && -f /etc/nginx/sites-available/$domain ]]; then
	if [[ ( -z $subfolder && $(is_wp $domain) == "false" ) || ( -n $subfolder && $(is_wp $domain $subfolder) == "false" ) ]]; then
		echo "${red}[ERROR] Site${blu} $domain$subfolder ${red}is not a WP site!${end}"
		exit 1
	fi
	
	check=$(is_wp_multisite $domain)
	if ! [[ $check =~ ^(subdomain|subdirectory|false)$ ]]; then
		echo "${red}[ERROR] Task aborted due to an error!${end}"
		exit 1
	elif [[ $check =~ ^(subdomain|subdirectory)$ ]]; then
		echo "${red}[ERROR] Site${blu} $domain$subfolder ${red}is already in multisite configuration!${end}"
		exit 1
	fi
	
	wp_multisite_convertion


# Parked Domain
elif [[ -n $parked && -n $domain ]]; then
	createsite
	parked_domain

	
# Reverse proxy
elif [[ -n $proxy && -n $domain ]]; then
	reverse_proxy
	
	
# Site disabled	
elif [[ -n $off && ! -L /etc/nginx/sites-enabled/$domain && -f /etc/nginx/sites-available/$domain ]]; then
		echo "${gre}Seems like your site${blu} $domain ${gre}is already disabled!${end}"
elif [[ -n $off && -L /etc/nginx/sites-enabled/$domain ]]; then
	api-events_update si5
	echo "${gre}Site${blu} $domain ${gre}has been successfully disabled!${end}"
	sudo rm /etc/nginx/sites-enabled/$domain

	
# Site re-enabled
elif [[ -n $on && -L /etc/nginx/sites-enabled/$domain ]]; then
	echo "${gre}Site${blu} $domain ${gre}is already enabled!${end}"
elif [[ -n $on && ! -L /etc/nginx/sites-enabled/$domain && -f /etc/nginx/sites-available/$domain ]]; then
	api-events_update si4
	sudo ln -s /etc/nginx/sites-available/$domain /etc/nginx/sites-enabled/$domain
	echo "${gre}Site${blu} $domain ${gre}has been successfully enabled!${end}"


# Redirection Manager
elif [[ -n $redirection && -f /etc/nginx/sites-available/$domain ]]; then
	check_for_nginx
	redirection_manager

	
# Delete site	
elif [[ -n $delete && -f /etc/nginx/sites-available/$domain ]]; then
	api-events_update si6
	if [[ $domain == "default" || $domain == $(conf_read tools-port) ]]; then
		echo "${red}[ERROR] System sites can not be removed!${end}"
		exit 1
	elif [[ -n $subfolder ]]; then
		if [[ ! -f /var/www/$domain/htdocs$subfolder/wp-config.php ]]; then
			echo "${red}[ERROR] Subfolder not found or is not a WP subsite!${end}"
			exit 1
		fi
		db_delete $domain
		sudo rm -rf /var/www/$domain/htdocs$subfolder
		sudo rm -rf /etc/nginx/apps.d/$domain$subname*.conf
		sudo sed -i "/# WebinolyCustom/,/# WebinolyCustomEnd/{/$domain$subname-php.conf/d}" /etc/nginx/sites-available/$domain
		sudo sed -i "/# WebinolyCustom/,/# WebinolyCustomEnd/{/$domain$subname-wpfc.conf/d}" /etc/nginx/sites-available/$domain
		echo "${gre}Subfolder${blu} $subfolder ${gre}from${blu} $domain ${gre}has been successfully deleted!${end}"
	else
		deletesite
	fi


# SSL (Letsencrypt)
elif [[ -n $ssl ]]; then
	if [[ $ssl == "renew" && -z $domain ]]; then
			# Post-Hook removed because we always restart nginx at the end of site command
			sudo certbot renew
	elif [[ ( $ssl == "on" || $ssl == "force-renewal" ) && -f /etc/nginx/sites-available/$domain ]]; then
		api-events_update si10
		if [[ $(is_ssl $domain) == "true" && $ssl != "force-renewal" ]]; then
			echo "${gre}SSL is already enabled for your site -${blu} $domain ${end}"
		elif [[ -n $ssl_crt || -n $ssl_key ]]; then
			if [[ -f $ssl_crt && -f $ssl_key ]]; then
				ssl_nginx
				echo "${gre}Your Custom SSL Cert have been successfully enabled on your site -${blu} $domain${end}"
			else
				echo "${red}[ERROR] Custom SSL cert files not found! ${end}"
				exit 1
			fi
		elif [[ -n $add_to_wildcard ]]; then
			if [[ $add_to_wildcard == true ]]; then
				echo "${gre}Please, enter a valid Wildcard SSL Domain! ${end}"
				read -p "${blu}Domain: ${end}" add_to_wildcard
				add_to_wildcard=${add_to_wildcard:-NeverMatchDotCom}
			fi
			
			# Check if domain is a subdomain that can be used in the wildcard cert.
			if [[ $domain == *.*."$add_to_wildcard" ]]; then
				echo "${red}[ERROR] Wildcard Certs only support first-level subdomains!${end}"
				exit 1
			elif [[ ! -d /etc/letsencrypt/live/$add_to_wildcard ]]; then
				echo "${red}[ERROR] Wildcard Cert not found!${end}"
				exit 1
			elif [[ $domain == *."$add_to_wildcard" ]]; then
				ssl_nginx
				[[ $(is_wp $domain) == "true" ]] && edit_wp_db_url $domain "https://${domain}"
				echo "${gre}Your site ${blu}- $domain -${gre} have been successfully added to the ${blu}- $add_to_wildcard -${gre} wildcard cert.${end}"
			else
				echo "${red}[ERROR] Seems like your site is not a valid subdomain!${end}"
				exit 1
			fi
		else
			site_ssl_on
		fi
	elif [[ $ssl == "off" && -f /etc/nginx/sites-available/$domain ]]; then
		api-events_update si11
		[[ $(is_ssl $domain) == "true" ]] && site_ssl_off || echo "${gre}SSL is already disabled for your site${blu} $domain ${end}"
	elif [[ $ssl == "off" && ! -f /etc/nginx/sites-available/$domain && -f /etc/letsencrypt/live/$domain/cert.pem ]]; then
		echo "${red}[WARNING] SSL Orphan-Cert found and will be revoked automatically!${end}"
		ssl_revoke
	elif [[ -n $domain && ! -f /etc/nginx/sites-available/$domain ]]; then
		echo "${red}[ERROR] Domain not found! ${end}"
		exit 1
	else
		echo "${red}[ERROR] Invalid value for SSL command! ${end}"
		exit 1
	fi

# FastCGI Cache
elif [[ -n $cache ]]; then
	wp_cache


# Force www or non-www redirect (www, root, off)
elif [[ -n $force_redirect && -f /etc/nginx/sites-available/$domain ]]; then
	force_redirect


# Yoast Sitemap support, per site.
elif [[ -n $yoast_sitemap && -f /etc/nginx/sites-available/$domain ]]; then
	yoast_sitemap


# Staging and Clone sites
elif [[ -n $clone_from ]]; then
	if [[ ! -f /etc/nginx/sites-available/$clone_from ]]; then
		echo "${red}[ERROR] Site/domain ${blu}'$clone_from'${red} not found!${end}"
		exit 1
	elif [[ -f /etc/nginx/sites-available/$domain && -z $subfolder ]]; then
		echo "${red}[ERROR] Can not create site${blu} $domain ${red}because already exists!${end}"
		exit 1
	elif [[ -f /etc/nginx/sites-available/$domain && -n $subfolder && -d /var/www/$domain/htdocs$subfolder ]]; then
		echo "${red}[ERROR] Subfolder ${blu}'$subfolder'${red} already exists!${end}"
		exit 1
	elif [[ $(is_wp $clone_from $subfolder) != "true" ]]; then
		echo "${red}[ERROR] Site${blu} '$clone_from' ${red}is not a WordPress site!${end}"
		exit 1
	elif [[ $(is_wp_installed $clone_from) != "true" ]]; then
		echo "${red}[ERROR] Seems like WordPress is still not configured in your${blu} '$clone_from' ${red}site!${end}"
		exit 1
	else
		clone_wp_site
	fi


# Replace Content
elif [[ -n $replace_content && -f /etc/nginx/sites-available/$domain ]]; then
	if [[ $(is_wp $domain $subfolder) != "true" ]]; then
		echo "${red}[ERROR] Site${blu} $domain ${red}is not a WordPress site!${end}"
		exit 1
	else
		wp_replace_content
	fi


# List Sites
elif [[ -n $list && -z $redirection ]]; then
	list_sites
	nginx_not="true" # Nginx-Reload not-needed.


# Catch ERROR 
elif [[ -n $domain && ! -f /etc/nginx/sites-available/$domain ]]; then
	echo "${red}[ERROR] Site${blu} $domain ${red}doesn't exists, please enter a valid domain name!${end}"
	exit 1
else
	echo "${red}[ERROR] Please, enter a valid option! ${end}"
	exit 1
fi

shopt -u extglob
[[ $(conf_read nginx) == "true" && -z $nginx_not ]] && sudo service nginx reload
api-events_update sie
