#!/bin/bash

# Let's Encrypt manual mode (for Reverse Proxy sites)
sudo mkdir -p $value/.well-known/acme-challenge
sudo touch $value/.well-known/acme-challenge/$CERTBOT_TOKEN
sudo echo $CERTBOT_VALIDATION > $value/.well-known/acme-challenge/$CERTBOT_TOKEN
