#!/bin/bash

# Don't remove dumb re-check!
# Prevent 'tput' errors when running from Cron
[[ -z $TERM || $TERM == "unknown" || $TERM == "dumb" ]] && export TERM=dumb

readonly app_version="1.12.0"
readonly svr_version="1.5"
readonly os_ubuntu_supported=(bionic focal)
readonly php_supported=(7.2 7.3 7.4)
readonly datadog_agent_ver="7"

# echo colors
readonly red=`tput setaf 1`
readonly gre=`tput setaf 2`
readonly blu=`tput setaf 6`
readonly end=`tput sgr0`
readonly bol=`tput bold`
readonly dim=`tput dim`

# STOP and exit if not root or sudo.
if [[ $(whoami) != "root" ]]; then
	echo "${red}Please run this script as root or using sudo.${end}"
	exit 1
fi


check_ubuntu_release() {
	local check="false"
	for val in "${os_ubuntu_supported[@]}"
	do 
		[[ $val == $1 ]] && check="true"
	done
	echo $check
}
check_php_version() {
	local check="false"
	for val in "${php_supported[@]}"
	do 
		[[ $val == $1 ]] && check="true"
	done
	echo $check
}

check_osname() {
	local distr=`echo $(lsb_release -i | cut -d':' -f 2)`
	local osver=`echo $(lsb_release -c | cut -d':' -f 2)`
	if ! [[ $distr == "Ubuntu" && $(check_ubuntu_release $osver) == "true" ]]; then
		echo "${red}" >&2
		echo "****************************************************************************" >&2
		echo "****  This OS is not supported by Webinoly and could not work properly  ****" >&2
		echo "****************************************************************************" >&2
		echo "${end}" >&2
	fi
	echo $osver
}


check_for_nginx() {
	if [[ $(conf_read nginx) != "true" && $1 == "-ask" ]]; then
		echo "${red}"
		echo "+ NGINX Not Found!"
		echo "${blu}Do you want to install it now? [y/N]? ${end}"
		while read -r -n 1 -s answer; do
			answer=${answer:-n}
			echo ""
			[[ $answer = [YyNn] ]] && break
		done
		
		[[ $answer == [Yy] ]] && sudo stack -nginx
	fi
	
	if [[ $(conf_read nginx) != "true" ]]; then
		echo "${red}[ERROR] NGINX is required and not found! ${end}"
		exit 1
	fi
}
check_for_nginx_tool() {
	if [[ $(conf_read nginx) != "true"  || $(conf_read nginx-optim) != "true" || $(conf_read nginx-tool) != "true" ]]; then
		echo "${red}[ERROR] NGINX Tools are required and not found! ${end}"
		exit 1
	fi
}
check_for_php() {
	if [[ $(conf_read php) != "true" && $1 == "-ask" ]]; then
		echo "${red}"
		echo "+ PHP Not Found!"
		echo "${blu}Do you want to install it now? [y/N]? ${end}"
		while read -r -n 1 -s answer; do
			answer=${answer:-n}
			echo ""
			[[ $answer = [YyNn] ]] && break
		done
		
		[[ $answer == [Yy] ]] && sudo stack -php
	fi
	
	if [[ $(conf_read php) != "true" ]]; then
		echo "${red}[ERROR] PHP is required and not found! ${end}"
		exit 1
	fi
}
check_for_php_tool() {
	if [[ $(conf_read php) != "true"  || $(conf_read php-optim) != "true" || $(conf_read php-tool) != "true" ]]; then
		echo "${red}[ERROR] PHP Tools are required and not found! ${end}"
		exit 1
	fi
}
check_for_mysql() {
	if [[ $(conf_read mysql) != "true" && $1 == "-ask" ]]; then
		echo "${red}"
		echo "+ MySQL Not Found!"
		echo "${blu}Do you want to install it now? [y/N]? ${end}"
		while read -r -n 1 -s answer; do
			answer=${answer:-n}
			echo ""
			[[ $answer = [YyNn] ]] && break
		done
		
		[[ $answer == [Yy] ]] && sudo stack -mysql
	fi
	
	if [[ $(conf_read mysql) != "true" ]]; then
		echo "${red}[ERROR] MySQL is required and not found! ${end}"
		exit 1
	fi
}
check_for_mysql_client() {
	if [[ $(conf_read mysql-client) != "true" ]]; then
		echo "${gre}MySQL Client is not installed and we need it to stablish a connection with your external server."
		echo "Wait while we install MySQL Client... installing!!!${end}"
		mysql_client_install > /dev/null 2>&1 &
		echo "${gre}MySQL Client has been successfully installed!${end}"
	fi
}


conf_read() {
	if [[ ! -f /opt/webinoly/webinoly.conf ]]; then
		echo "${red}[ERROR] Config file not found!${end}"
		exit 1
	fi
	
	local val=$(grep -w "^${1}:.*" /opt/webinoly/webinoly.conf | cut -f 2 -d ':')
	echo $val
}

conf_delete() {
	if [[ ! -f /opt/webinoly/webinoly.conf ]]; then
		echo "${red}[ERROR] Config file not found!${end}"
		exit 1
	fi
	
	sed -i "/^${1}:/d" /opt/webinoly/webinoly.conf
}

conf_write() {
	[[ ! -f /opt/webinoly/webinoly.conf ]] && sudo touch /opt/webinoly/webinoly.conf
	conf_delete $1
	echo "$1:$2" >> /opt/webinoly/webinoly.conf
}


wp_dbdata() {
	local domain="$1"
	
	# Get dbname and dbuser of a WP site
	if [[ -f /var/www/$domain/htdocs$subfolder/wp-config.php ]]; then
		wpconfpath="/var/www/$domain/htdocs$subfolder/wp-config.php"
	elif [[ -f /var/www/$domain/wp-config.php ]]; then
		wpconfpath="/var/www/$domain/wp-config.php"
	elif [[ $(is_wp $domain) == "true" && $(is_parked $domain) == "true" ]]; then
		wpconfpath="$(grep -G "root .*;" /etc/nginx/sites-available/$domain | sed -r 's/^.*root (.*)htdocs;$/\1/')wp-config.php"
	else
		return
	fi
	
	wp_dbname=$( grep -F "DB_NAME" $wpconfpath | cut -f 4 -d "'" -s)
	wp_dbuser=$( grep -F "DB_USER" $wpconfpath | cut -f 4 -d "'" -s)
	wp_dbhost=$( grep -F "DB_HOST" $wpconfpath | cut -f 4 -d "'" -s)
	wp_dburl=$(echo "$wp_dbhost" | cut -f 1 -d ':')
	wp_dbport=$(echo "$wp_dbhost" | cut -f 2 -d ':' -s)
	wp_dbpref=$( grep -F "table_prefix" $wpconfpath | cut -f 2 -d "'" -s)
	
	[[ ${wp_dbhost,,} == "localhost" ]] && wp_dbhost=${wp_dbhost,,}
	[[ -z $wp_dbport ]] && wp_dbport="3306"
	
	if [[ -z $external_db && -n $wp_dbhost && $wp_dbhost != "localhost" ]]; then
		echo "" >&2
		echo "${gre}External DB${blu} '${wp_dburl}:${wp_dbport}' ${gre}found in${blu} $domain ${gre}(Press 'Enter' key twice to skip)" >&2
		read -p "${blu}External DB root username [root]: " wp_uroot
		wp_uroot=${wp_uroot:-root}
		read -p "External DB root password: " wp_proot
		
		external_db="[$wp_uroot,$wp_proot]"
	elif [[ -n $external_db ]]; then
		dbdata=${external_db:1:-1}
		wp_uroot=$(echo "${dbdata}" | cut -d',' -f 1 -s)
		wp_proot=$(echo "${dbdata}" | cut -d',' -f 2 -s)
		if [[ $(echo "${external_db}" | cut -c-1) != "[" || $(echo "${external_db}" | rev | cut -c-1) != "]" || -z $wp_uroot || -z $wp_proot ]]; then
			echo "${red}[ERROR] Invalid data for External Database!${end}" >&2
			exit 1
		fi
	fi
}


pre_install() {
	sudo apt -qq update
	if [[ $(conf_read pre-packs) != true ]]; then
		# Check for missing essential packages
		api-events_update i1
		sudo apt -y -qq install dialog
		sudo apt -y -qq install software-properties-common
		sudo apt -y -qq install pwgen
		sudo apt -y -qq install unzip
		sudo apt -y -qq install zip
		conf_write pre-packs true
		api-events_update i2
	fi
}


# Remove Installation Files
app_purge() {
	sudo rm $HOME/webinoly.tar
	sudo rm -rf /opt/webinoly/plugins
}


mysql_client_install() {
	api-events_update im2
	
	# Cases with MariaDB v10.4 support - https://downloads.mariadb.org/mariadb/repositories/
	sudo apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc'
	sudo add-apt-repository "deb [arch=amd64,arm64,ppc64el] http://mirrors.syringanetworks.net/mariadb/repo/10.4/ubuntu $(check_osname) main"
	
	pre_install
	sudo apt -y install mariadb-client
	conf_write mysql-client true
	echo "${gre}MySQL Client has been successfully installed!${end}"
	api-events_update im3
}


tools_port() {
	local in="$1"
	while ! [[ $port -ge 0 && $port -le 65535 && $port =~ ^[0-9]+$ ]] 2>/dev/null
	do
		if [[ -z "$in" || $in == "empty" ]]; then
			read -p "${blu}Tools Port [Default: 22222]: " port
			port=${port:-22222}
		else
			port="$in"
			in="empty"
		fi
	done
	conf_write tools-port $port
	echo "${gre}Port $port has been enabled to access all your Tools! ${end}"
}


api-events_update() {
	conf_write status-api $1
	if [[ -f /opt/webinoly/lib/api-events ]]; then
		source /opt/webinoly/lib/api-events
		api-events_catch_status $1
	fi
}


remove_nginx_default_server() {
	if [[ -n $1 && -f /etc/nginx/sites-available/$1 ]]; then
		sudo sed -i "s/listen 80 default_server;/listen 80;/" /etc/nginx/sites-available/$1
		sudo sed -i "s/listen \[::\]:80 default_server;/listen [::]:80;/" /etc/nginx/sites-available/$1
		sudo sed -i "s/listen 443 ssl http2 default_server;/listen 443 ssl http2;/" /etc/nginx/sites-available/$1
		sudo sed -i "s/listen \[::\]:443 ssl http2 default_server;/listen [::]:443 ssl http2;/" /etc/nginx/sites-available/$1
		sudo sed -i '/WebinolyStartBlackhole/,/WebinolyEndBlackhole/{/.*/d}' /etc/nginx/sites-available/$1
	fi
}


check_for_parameters() {
	# Global variables: domain, tld, subdomain, main_domain, sub_domain, empty_param
	
	# Check for domain parameter if is first parameter and have no hyphen at the begining.
	if [[ -n $1 && $(echo $1 | cut -c-1) != "-" ]]; then
		domain=$1
		shift
		
		local count=1
		while true; do
			tld=$(echo $domain | cut -d'.' -f ${count}- -s)
			if grep -Fxq "$tld" /opt/webinoly/lib/public_suffix_list.dat || [ -z $tld ]; then
				break
			fi
			count=$[$count+1]
		done
		[[ $count -gt 2 ]] && subdomain="true" || subdomain="false"
		
		if [[ $subdomain == "true" && -n $tld ]]; then
			main_domain=$(echo $domain | cut -d'.' -f $[$count-1]- -s)
			sub_domain=$(echo $domain | cut -d'.' -f -$[$count-2] -s)
		fi
	fi
	
	for arg in $@; do
		local check=$(echo "${arg}" | cut -c-1)
		local arg=${arg:1}
		local par=$(echo "${arg}" | cut -d'=' -f 1 -s)
		local val=$(echo "${arg}" | cut -d'=' -f 2 -s)
		[[ -z $par ]] && par=$arg
		[[ -z $val && $par == "conf-value_"* ]] && val="NeverMatchString" #Special value to allow the string "true" as a valid value.
		[[ -z $val ]] && val=true
		
		# Check for Webinoly -conf-value_
		if [[ $par == "conf-value_"* ]]; then
			dyn_var=$(echo "${par}" | cut -d'_' -f 2 -s)
			par=$(echo "${par}" | cut -d'_' -f 1 -s)
		fi
		
		# Convert to lowercase and support for hyphen in arguments.
		par=${par,,}
		par=$(echo $par | sed "s/-/_/g")
		
		# Only valid variables names and check for begin with hyphen.
		if [[ $check == "-" && $par =~ ^[a-zA-Z_][a-zA-Z_0-9]*$ ]]; then
			[[ -n $par ]] && eval $par=\$val
		else
			echo "${red}[ERROR] Invalid parameters! ${end}"
			exit 1
		fi
	done
	[[ -z $@ ]] && empty_param="true"
}


is_ip() {
	# Check for valid IPv4 and IPv6 values, including CIDR.
	if [[ -n $1 && $1 =~ ^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\/([0-9]|[1-2][0-9]|3[0-2]))?$ || $1 =~ ^(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))(\/([0-9]|[1-9][0-9]|1[0-2][0-8]))?$ ]]; then
		echo "true"
	else
		echo "false"
	fi
}


is_domain() {
	# Only numerals 0-9, basic Latin letters, both lowercase and uppercase, hyphen.
	if ! [[ $1 =~ ^[\.0-9A-Za-z\-]+$ ]]; then
		echo "false"
	
	# Check Lenght
	elif [[ ${#1} -gt 67 ]]; then
		echo "false"
		
	# Can not start or end with a hyphen
	elif [[ $(echo "${1}" | cut -c-1) == "-" || $(echo "${1}" | rev | cut -c-1) == "-" ]]; then
		echo "false"
	
	# Can not contain two points together and can not start or end with a point
	elif [[ $1 == *..* || $(echo "${1}" | cut -c-1) == "." || $(echo "${1}" | rev | cut -c-1) == "." ]]; then
		echo "false"
	
	else
		echo "true"
	fi
}


is_url_path() {
	# Should start with / and after that all should be valid characters.
	if [[ -n $1 && $1 =~ ^\/([\]A-Za-z0-9_\/\.-:\!\*\'\[\(\)\;@\&\=\+\$\,\?#\~\%]+)?$ ]]; then
		echo "true"
	else
		echo "false"
	fi
}


is_url() {
	# Output: true,http,https,false  Example: $(is_url $domain)
	# Global variables when -split is set: url_scheme, url_host, url_path, url_port    Example: is_url $domain -split
	
	local scheme=$(echo "${1,,}" | cut -d':' -f 1 -s)
	local host=$(echo "${1,,}" | cut -d':' -f 2 -s | cut -d'/' -f 3 -s)
	local path=$(echo "${1,,}" | cut -d':' -f 2- -s | cut -d'/' -f 4- -s)
	local port=$(echo "${1,,}" | cut -d':' -f 3 -s | cut -d'/' -f 1 )
	local out="false"
	
	# In case of no-scheme format
	local hosted=$(echo "${1,,}" | cut -d'/' -f 1)
	# In case of no-scheme have port included
	[[ $(echo $hosted | cut -d':' -f 2 -s) =~ ^[0-9]+$ ]] && hosted=$(echo $hosted | cut -d':' -f 1)
	
	if [[ $scheme =~ ^(http|https)$ ]]; then	
		if [[ $(is_domain $host) != "true" ]]; then
			out="false"
		elif [[ -n $path && $(is_url_path /$path) != "true" ]]; then
			out="false"
		elif [[ -n $port ]] && ! [[ $port =~ ^[0-9]+$ && $port -ge 0 && $port -le 65535 ]]; then
			out="false"
		else
			out=$scheme
		fi
	elif [[ $(is_domain $hosted) == "true" ]]; then
		scheme=""
		host=$hosted
		path=$(echo "${1,,}" | cut -d'/' -f 2- -s)
		port=$(echo "${1,,}" | cut -d'/' -f 1 | cut -d':' -f 2 -s)
		
		if [[ -n $path && $(is_url_path /$path) != "true" ]]; then
			out="false"
		elif [[ -n $port ]] && ! [[ $port =~ ^[0-9]+$ && $port -ge 0 && $port -le 65535 ]]; then
			out="false"
		else
			out="true"
		fi
	else
		out="false"
	fi
	
	if [[ $2 == "-split" && $out != "false" ]]; then
		url_scheme=$scheme
		url_host=$host
		[[ -n $path ]] && url_path="/$path"
		url_port=$port
	elif [[ $2 != "-split" ]]; then
		echo $out
	fi
}


is_ssl() {
	[[ -f /etc/nginx/sites-available/$1 && -n $(sed -n -e '/WebinolyNginxServerStart/,$p' /etc/nginx/sites-available/$1 | grep -F "ssl_certificate_key") ]] && echo "true" || echo "false"
}

is_html_only() {
	local ndx=$(sed -n -e '/WebinolyNginxServerStart/,$p' /etc/nginx/sites-available/$1 | grep -E "index .?index.html index.htm")
	local loc=$(sed -n -e '/WebinolyNginxServerStart/,$p' /etc/nginx/sites-available/$1 | grep -F "location / { try_files ")
	[[ -f /etc/nginx/sites-available/$1 && -n $ndx && -n $loc && $(is_php $1) != "true" && $(is_wp $1) != "true" ]] && echo "true" || echo "false"
}

is_php() {
	local php=$(sed -n -e '/WebinolyNginxServerStart/,$p' /etc/nginx/sites-available/$1 | grep -F " common/php.conf;")
	local phpx=$(sed -n -e '/WebinolyNginxServerStart/,$p' /etc/nginx/sites-available/$1 | grep -F " common/phpx.conf;")
	[[ -f /etc/nginx/sites-available/$1 && ( -n $php || -n $phpx ) && $(is_wp $1) == "false" ]] && echo "true" || echo "false"
}

is_wp() {
	# $1 = domain, $2 = WP subfolder
	[[ -n $2 ]] && local subname=$(echo $2 | sed "s/\//_/g")
	if [[ -z $2 && -f /etc/nginx/sites-available/$1 && -n $(sed -n -e '/WebinolyNginxServerStart/,$p' /etc/nginx/sites-available/$1 | grep -F " common/wpcommon") ]]; then
		echo "true"
	elif [[ -n $2 && -f /etc/nginx/sites-available/$1 && -f /etc/nginx/apps.d/$1$subname-wpcommon.conf && -f /var/www/$1/htdocs$2/wp-config.php ]]; then
		echo "true"
	else
		echo "false"
	fi
}

is_wp_cache() {
	# $1 = domain, $2 = WP subfolder
	[[ -n $2 ]] && local subname=$(echo $2 | sed "s/\//_/g")
	if [[ -z $2 && -f /etc/nginx/sites-available/$1 && -n $(sed -n -e '/WebinolyNginxServerStart/,$p' /etc/nginx/sites-available/$1 | grep -F " common/wpfc.conf;") ]]; then
		echo "true"
	elif [[ -n $2 && -f /etc/nginx/sites-available/$1 && -n $(sed -n -e '/# WebinolyCustom/,$p' /etc/nginx/sites-available/$1 | grep -F "$1$subname-wpfc.conf;") ]]; then
		echo "true"
	else
		echo "false"
	fi
}

is_wp_multisite() {
	wp_dbdata $1
	local dbsetup="SELECT * FROM information_schema.tables WHERE table_schema = '$wp_dbname' AND table_name = '${wp_dbpref}sitemeta' LIMIT 1;"
	local dbsetuc="USE $wp_dbname; SELECT meta_value FROM ${wp_dbpref}sitemeta where meta_key='subdomain_install';"
	
	if [[ $wp_dbhost == "localhost" ]]; then
		local ROOT_PASS=$( echo $(conf_read mysql-root) | openssl enc -d -a -salt )
		wpmu=$(sudo mysql --connect-timeout=10 --user=root -p$ROOT_PASS -e "$dbsetup")
		[[ -n $wpmu ]] && mutype=$(sudo mysql --connect-timeout=10 --user=root -p$ROOT_PASS -e "$dbsetuc")
	elif [[ -n $wp_dburl ]]; then
		wpmu=$(sudo mysql --connect-timeout=10 -h "$wp_dburl" -P "$wp_dbport" -u"$wp_uroot" -p"$wp_proot" -e "$dbsetup")
		[[ -n $wpmu ]] && mutype=$(sudo mysql --connect-timeout=10 -h "$wp_dburl" -P "$wp_dbport" -u"$wp_uroot" -p"$wp_proot" -e "$dbsetuc")
	fi
	
	if [[ $(echo $mutype | cut -f 2 -d " " -s) == "1" ]]; then
		echo "subdomain"
	elif [[ -n $wpmu ]]; then
		echo "subdirectory"
	else
		echo "false"
	fi
}


is_wp_installed() {
	# This function check if WP db exists.
	# When you create a WP site, DB is created only after the initial WP installation wizard is completed.
	
	wp_dbdata $1
	local dbsetup="SELECT * FROM information_schema.tables WHERE table_schema = '$wp_dbname' AND table_name = '${wp_dbpref}options' LIMIT 1;"
	
	if [[ $wp_dbhost == "localhost" ]]; then
		local ROOT_PASS=$( echo $(conf_read mysql-root) | openssl enc -d -a -salt )
		[[ -n $(sudo mysql --connect-timeout=10 --user=root -p$ROOT_PASS -e "$dbsetup") ]] && echo "true" || echo "false"
	elif [[ -n $wp_dburl ]]; then
		[[ -n $(sudo mysql --connect-timeout=10 -h "$wp_dburl" -P "$wp_dbport" -u"$wp_uroot" -p"$wp_proot" -e "$dbsetup") ]] && echo "true" || echo "false"
	else
		echo "false"
	fi
}


is_proxy() {
	[[ -f /etc/nginx/sites-available/$1 && -n $(sed -n -e '/WebinolyNginxServerStart/,$p' /etc/nginx/sites-available/$1 | grep -F "proxy_pass") ]] && echo "true" || echo "false"
}

is_parked() {
	[[ -f /etc/nginx/sites-available/$1 && ! -d /var/www/$1 && $(is_proxy $1) == "false" ]] && echo "true" || echo "false"
}


is_dd_log() {
	if [[ $1 == "nginx" ]]; then
		local ddpath="/etc/datadog-agent/conf.d/nginx.d/conf.yaml"
	elif [[ $1 == "fpm" ]]; then
		local ddpath="/etc/datadog-agent/conf.d/php_fpm.d/conf.yaml"
	elif [[ $1 == "mysql" ]]; then
		local ddpath="/etc/datadog-agent/conf.d/mysql.d/conf.yaml"
	elif [[ $1 == "redis" ]]; then
		local ddpath="/etc/datadog-agent/conf.d/redisdb.d/conf.yaml"
	elif [[ $1 == "global" ]]; then
		[[ -f /etc/datadog-agent/datadog.yaml && -n $(grep -F "WebinolyLogsStart" /etc/datadog-agent/datadog.yaml) ]] && local global="true"
	else
		local ddpath=""
	fi
	
	[[ -n $global || ( -n $ddpath && -f $ddpath && -n $(grep -F "WebinolyDatadogLogsStart" $ddpath)) ]] && echo "true" || echo "false"
}


is_log() {
	[[ -f /etc/nginx/sites-available/$1 && -n $(sed -n -e '/WebinolyNginxServerStart/,$p' /etc/nginx/sites-available/$1 | grep -F "nginx/$1.access.log ") ]] && echo "true" || echo "false"
}

