#!/bin/bash

echo "${red}"
echo "Your server configuration will be updated and all changes you manually did will be lost!!"
echo "${blu}Current server version 'v$oldver' will be upgraded to the newest 'v$newver'. Wait...${end}"

onezero_to_oneone() {
	
	if [[ $(conf_read mysql-tool) == "true" ]]; then
		# Remove old phpMyAdmin
		echo "phpmyadmin      phpmyadmin/dbconfig-remove      boolean true" | debconf-set-selections
		echo "phpmyadmin      phpmyadmin/purge        boolean true" | debconf-set-selections
		sudo apt-get -y purge phpmyadmin
		sudo apt-get -y autoremove
		sudo rm -rf /var/www/$(conf_read tools-port)/htdocs/pma
		conf_write mysql-tool purged
		
		# Install new phpMyAdmin
		sudo stack -pma
	fi
	
	if [[ $(conf_read nginx-tool) == "true" ]]; then
		# Install LetsEncrypt
		echo | sudo add-apt-repository ppa:certbot/certbot
		pre_install
		sudo apt-get -y install certbot
		
		cronrene=$( sudo grep -F "letsencrypt renew" /var/spool/cron/crontabs/root )
		[[ -n $cronrene ]] && sudo sed -i '/letsencrypt renew/c\15 3 * * 7 certbot renew --post-hook "service nginx restart"' /var/spool/cron/crontabs/root
		
		sudo echo "
staple-ocsp = True
must-staple = True" | tee -a /etc/letsencrypt/cli.ini

		for site in "/etc/nginx/sites-available"/*
		do
			domi=$(echo $site | cut -f 5 -d "/")
			[[ $domi != "html" && $domi != $(conf_read tools-port) ]] && sudo sed -i "/#include \/var\/www\//c\	include /var/www/$domi/*-nginx.conf;" /etc/nginx/sites-available/$domi
		done
	fi
	
}


oneone_to_onetwo() {
	# Forgot doing it in 1.1 update
	sudo apt-get -y install zip
}


onetwo_to_onethree() {
	# Nginx "ssl on" directive is now deprecated - remove it!
	for site in "/etc/nginx/sites-available"/*
	do
		domi=$(echo $site | cut -f 5 -d "/")
		[[ $domi != "html" && $domi != 22222 ]] && sudo sed -i "/ssl on;/c\	#ssl on;" /etc/nginx/sites-available/$domi
	done
	
	# swappines is now included by default in linux optimization.
	sudo sed -i '/vm.swappiness/d' /etc/sysctl.conf

	# Now we need a backup of default Nginx file for "default-site" command.
	[[ -a /etc/nginx/sites-available/default ]] && sudo cp -p /etc/nginx/sites-available/default /opt/webinoly/templates/source/
	
	# Upgrade MariaDB 10.2 to 10.3
	if [[ $(conf_read mysql) == "true" ]]; then
		sudo stack -mysql -purge=keep-data
		sudo stack -mysql
	fi
	
}


# Version numbers without point
[[ ${oldver//.} -lt 11 ]] && onezero_to_oneone > /dev/null 2>&1 &
wait $!
[[ ${oldver//.} -lt 12 ]] && oneone_to_onetwo > /dev/null 2>&1 &
wait $!
[[ ${oldver//.} -lt 13 ]] && onetwo_to_onethree > /dev/null 2>&1 &
wait $!


sudo webinoly -server-reset

echo "${gre}Your server-configuration has been successfully updated!${end}"
